name: Deploy to Maven Central

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (or the Java version you are using)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      # Import GPG private key from GitHub secrets and configure GPG
      - name: Import GPG private key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          
      - name: Configure GPG
        run: |
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg.conf

      # Build and deploy the artifact to Maven Central
      - name: Build and Deploy to Maven Central
        run: mvn clean deploy -DskipTests -P release
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
